[package]
name = "devenv"
version = "1.1.0"
edition.workspace = true
license.workspace = true

# Make `cargo run` default to the devenv CLI
default-run = "devenv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansiterm.workspace = true
assert_matches = "1.5.0"
clap.workspace = true
cli-table.workspace = true
crossterm = "0.28.1"
dotlock.workspace = true
fs2.workspace = true
hex.workspace = true
include_dir.workspace = true
indoc.workspace = true
miette.workspace = true
nix.workspace = true
petgraph = "0.6.5"
regex.workspace = true
reqwest.workspace = true
schemars.workspace = true
schematic.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tempdir.workspace = true
tempfile = "3.12.0"
test-log = { version = "0.2.16", features = ["trace"] }
thiserror = "1.0.63"
tokio = { version = "1.39.3", features = [
    "process",
    "macros",
    "rt-multi-thread",
] }
tracing.workspace = true
which.workspace = true
whoami.workspace = true
xdg.workspace = true
