[package]
name = "devenv-run-tests"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
tempdir.workspace = true

devenv= { path = "../devenv" }
tokio = "1.39.3"
